### ISSUE TITLE
command redirects

### ISSUE THREAD

**Issue by MRSKnshnn** [THEWHITEBOY503/ConnMudaeClone#12]
some ppl use the wrong commands and it spits out a long error, here's a few suggestions for commands that redirect to other commands

!draw, commonly mistaken as !pull, !Draw, !drawcard, etc
!cardview, commonly mistaken as !viewcard
!view, commonly mistaken as !collection

**Comment by THEWHITEBOY503** [comment]
The confusing ass error messages that get spit out when an invalid command have been removed, so I'm not terribly sure this is needed. Will still implement this upon request.

**Comment by THEWHITEBOY503** [comment]
Closing issue. See comment:

> The confusing ass error messages that get spit out when an invalid command have been removed, so I'm not terribly sure this is needed. Will still implement this upon request.
