### ISSUE TITLE
collection pages

### ISSUE THREAD

**Issue by MRSKnshnn** [THEWHITEBOY503/ConnMudaeClone#14]
if possible, flooding could be avoided by implementing a page system to user's collection, similar to the scrolling on the admin (server deck) ver. of !cardview, maybe 9 or so cards a page

**Comment by THEWHITEBOY503** [comment]
I think I can just copy the scrolling system from `!cardview`, and if needed, implement a separate command that has a list, like the current `!view` command.

**Comment by THEWHITEBOY503** [comment]
Adding bug label to this because of the 25 per page error. Still working on figuring out how to paginate the responses.

**Comment by THEWHITEBOY503** [comment]
Pagination complete! (God damn, that took forever)
Awaiting push to main branch.
