### ISSUE TITLE
gift command

### ISSUE THREAD

**Issue by MRSKnshnn** [THEWHITEBOY503/ConnMudaeClone#19]
suggested by someone in the gen:unite server; a command similar to !trade where you can give someone a card, but they don't have to give you anything in return. basically just smthn like !gift (id) (user) and it would just give that card to the target user

**Comment by THEWHITEBOY503** [comment]
This one could be done pretty easy, I'd just copy paste the code from the trade command, change the syntax and remove the lines where it prompts for confirmation.
Should I make it prompt to confirm from the sender, receiver, both, or none?

**Comment by MRSKnshnn** [comment]
i think sender confirmation would be enough, that way it can be a surprise(????? pings still happen but idk. nice gestures)

**Comment by THEWHITEBOY503** [comment]
I can make it work like this:
```
User: !gift 1234 @Example (or user ID)
Bot: @User, would you like to send card Example Card (1234) to Example? Reply 'yes' or 'no'.
User: yes
Bot: @Example, @User has gifted you Example Card (1234)!

**Comment by THEWHITEBOY503** [comment]
I'll try and implement this later tonight.

**Comment by THEWHITEBOY503** [comment]
Added to beta bot. Pushing change to main bot around midnight tonight, pushing code to repo now.

**Comment by THEWHITEBOY503** [comment]
Pushed to repo. See [commit 2824aa1](https://github.com/THEWHITEBOY503/ConnMudaeClone/commit/2824aa1f6b0a3101f138a1d4dfd3b8baca7a2533).
