### ISSUE TITLE
(repost-ish) drawn cards and duplicates

### ISSUE THREAD

**Issue by MRSKnshnn** [THEWHITEBOY503/ConnMudaeClone#2]
duplicate cards should also be put into a user's collection with the same card id, though i understand how this may have issues in terms of coding.
when referring to cards in other commands by id, perhaps there could be a way to check how many cards of that id the user has, and if a card is removed/traded/etc and they have multiples of that card, maybe it could just pick any of the multiples to remove in that instance
though i'm not sure if that would be more code or if there's just a more convenient way of going about it lol, i figure you probably have something in mind for the issue

**Comment by THEWHITEBOY503** [comment]
One potential fix to this is to assign a **draw_id** to a users card every time it's drawn, which is a randomly generated ID number for that transaction. That way, if a user requests to modify their card (remove, trade, etc) and there's several, the program will gather all the **draw_id**s and select one at random to drop

**Comment by THEWHITEBOY503** [comment]
Every time a card is drawn, it gets assigned a randomly generated `draw_id`. If a user attempts to remove a card in their collection that they own more than one of, the program selects one of the draw_ids of the cards with matching IDs at random, then deletes the card with that draw_id.
