### ISSUE TITLE
(repost-ish) cooldown stuff

### ISSUE THREAD

**Issue by MRSKnshnn** [THEWHITEBOY503/ConnMudaeClone#4]
ideally, the bot would have an admin command that allows a server admin to set the cooldown for the bot, default being 6 hours. not much to say aside from that on this feature lol

**Comment by THEWHITEBOY503** [comment]
Implemented 3/10/23: A cooldown is now checked every time the `!draw` command is run. Default cooldown time is 6 hours, but the hours between draws can be set by a server admin with the `!setcooldown <hours>`  command
