### ISSUE TITLE
(me organizing my thoughts and reposting lol) card add/remove

### ISSUE THREAD

**Issue by MRSKnshnn** [THEWHITEBOY503/ConnMudaeClone#5]
for the commands to add and remove cards from the general database, 4 values would be needed. a command for it would look something possibly like this:
`!cardadd <name> <ID> <rarity value> <image>`, in use: `!cardadd [Insert Name (and other naming convention stuff)] ID101 1 url.link`
unsure if the names having spaces would cause issues. i figure there's ways with discord app commands to put spaces into different value slots in the command. not sure what exactly to call it, but i've seen it with a few bots and wonder if that's still doable. ids would not have spaces though, figures it's a lot more convenient to code that way
as for the image url, i wonder if it would be more convenient to do what mudae does and grab the image from an imgur link or use a discord media link instead. whichever works best and doesn't cause too much trouble, though

**Comment by THEWHITEBOY503** [comment]
added !add_card 
current syntax is 
`!add_card "<Card name>" <ID> "<Image Link>" "<Color code in 0xFFFFFF format>" <rarity>`

**Comment by THEWHITEBOY503** [comment]
added `!remove card <ID>`
