### ISSUE TITLE
(again trying to organize my thoughts) trading oh god

### ISSUE THREAD

**Issue by MRSKnshnn** [THEWHITEBOY503/ConnMudaeClone#6]
trading commands and the general flow of a trade interaction would probably work something along these lines:

> user1: !trade @user2 (card1 ID Here)

if user1 doesn't have card1 --
> bot: @user1, you do not have that card in your collection!

if user1 has card1 --
> bot: @user2, @user1 wants to trade (card1 name). Respond with the ID of the card you want to trade or say "decline" to decline the trade.

if user2 declines or if user2 doesn't respond for 60 sec --
> bot: Trade cancelled, @user1.

if user2 types the id of a card they don't have--
> bot: @user2, you do not have that card in your collection! Trade cancelled, @user1.

if user2 types the id of a card they do have--
> bot: @user1, @user2 wants to trade (card2 name) in exchange for (card1 name). Say "accept" to accept the trade or "decline" to decline the trade.

if user1 declines or if user1 doesn't respond for 60 sec --
> bot: Trade cancelled, @user2.

if user1 accepts --
> bot: @user1 traded (card1 name) in exchange for (card2 name) from @user2!

ok now that the confusing ill-formatted flow tree above is over.
once the trade is confirmed, figures it could probably work like remove card1 from user1's collection and add the same card to user2's collection, vice versa to both users
also feel free to simplify as much as needed

**Comment by THEWHITEBOY503** [comment]
Working on this one but it might be a little hard to test since it requires two people

**Comment by THEWHITEBOY503** [comment]
User 1: `!trade <ID> @User2`
Bot: `@User1 wants to trade card ID <ID> with you. Please respond with the card ID you wish to trade, or type decline to decline.`
User 2: `4471`
Bot: `Trade complete! @Connah now has card ID 4471, and @testaccount1738aye has card ID 3.`
