### ISSUE TITLE
(repost-ish) card viewing

### ISSUE THREAD

**Issue by MRSKnshnn** [THEWHITEBOY503/ConnMudaeClone#7]
to view their collection, a user would use `!collection` and the bot would spit out a list of their cards formatted like
`(card name) (card ID)` with each card in its own line. in use something like `Name Here (and other naming stuff) [IDtag]`

to view a card in their collection, a user would use `!view <card ID>`
if they have that card in their collection, then same sort of display as the way the `!draw` commands shows cards (with name, id, embed)
if they don't bot would say smthn like `@user, you don't have that card in your collection!`

**Comment by MRSKnshnn** [comment]
since collections will probably end up getting very long, perhaps some sort of thing with the embed where you can scroll through pages? like maybe a limit of 9 cards per page (simulating a trading card holder page), then you use a reaction to scroll back and forward different pages

**Comment by THEWHITEBOY503** [comment]
### Current progress:
- !view command added
- Bot outputs working embed
- Embed color and picture are selected from the first card in the database
### To-Do: 
- Add ability to view specific card ID
- Add pages for easier viewing

**Comment by THEWHITEBOY503** [comment]
Feature finished.
!view- view cards in user's collection
!cardview- display cards in server database
!cardview <Card ID> - displays specific card
