### ISSUE TITLE
database viewing

### ISSUE THREAD

**Issue by MRSKnshnn** [THEWHITEBOY503/ConnMudaeClone#8]
had the idea for an admin-only command that spits out a list of all the current cards in the general card database, that way admins can look at what cards they need to remove etc, just general organizational stuff
probably just name + id the same way the collection cmd works

**Comment by THEWHITEBOY503** [comment]
So, basically a command that lists all the user's cards across the server?

### Example:
User A has card 1, User B has cards 2 and 3, and User C has cards 1 and 3. `!servercards` returns:
```
CARDS:
User A - Card 1 
User B - Card 2 
User B - Card 3
User C - Card 3
User C - Card 1
```

**Comment by MRSKnshnn** [comment]
moreso just something that shows what cards are currently available to be drawn, figures the need to see users + their cards could fall under just making ppl use their view commands

**Comment by THEWHITEBOY503** [comment]
Oh, so basically a command that prints out the cards database. I can do that

**Comment by THEWHITEBOY503** [comment]
implemented a list command (!cardview) and a command to scroll through the cards one-by-one(!scardview, short for scrolling card view). will rewrite !view later.
