### ISSUE TITLE
collection "bias" selection

### ISSUE THREAD

**Issue by MRSKnshnn** [THEWHITEBOY503/ConnMudaeClone#9]
this one is honestly just kind of a silly feature, not too needed. basically the user would use !bias (card id) and it would set that card as their top card in their collection if they have the card. so at the top of the first page of their collection, image would be the collection embed image, card's color would be the collection embed color

**Comment by THEWHITEBOY503** [comment]
`bias <Card ID>` will set a card as your top card. 
`!resetbias` will remove your top card.
